-- Estrutura do Painel do Dono do MahaFinance.
-- Depois de aplicar esta migration, ative public.hook_controlar_cadastros
-- em Authentication > Hooks > Before User Created no painel do Supabase.

alter table public.profiles
  add column if not exists bloqueado boolean not null default false;

update public.profiles
set plano = lower(trim(coalesce(plano, 'free')));

update public.profiles
set plano = 'free'
where plano not in ('free', 'premium', 'dono');

do $$
declare
  constraint_name text;
begin
  for constraint_name in
    select con.conname
    from pg_constraint con
    join pg_attribute attr
      on attr.attrelid = con.conrelid
     and attr.attnum = any (con.conkey)
    where con.conrelid = 'public.profiles'::regclass
      and con.contype = 'c'
      and attr.attname = 'plano'
  loop
    execute format(
      'alter table public.profiles drop constraint %I',
      constraint_name
    );
  end loop;
end
$$;

alter table public.profiles
  alter column plano set default 'free',
  alter column plano set not null;

alter table public.profiles
  add constraint profiles_plano_valido
  check (plano in ('free', 'premium', 'dono'));

-- O usuário pode editar os próprios dados visuais, mas nunca promover a
-- própria conta, bloquear/desbloquear alguém ou criar/remover perfis à mão.
revoke insert, delete, update on public.profiles
  from public, anon, authenticated;

revoke update (plano, bloqueado)
  on public.profiles
  from public, anon, authenticated;

grant update (nome, avatar_url, moeda, tema)
  on public.profiles
  to authenticated;

grant select, insert, update, delete
  on public.profiles
  to service_role;

create index if not exists profiles_plano_idx
  on public.profiles (plano);

create index if not exists profiles_bloqueado_idx
  on public.profiles (bloqueado)
  where bloqueado = true;

create table if not exists public.app_settings (
  id text primary key default 'global'
    check (id = 'global'),
  cadastros_liberados boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users (id) on delete set null
);

insert into public.app_settings (id, cadastros_liberados)
values ('global', true)
on conflict (id) do nothing;

alter table public.app_settings enable row level security;

drop policy if exists "Leitura publica da disponibilidade de cadastro"
  on public.app_settings;

create policy "Leitura publica da disponibilidade de cadastro"
  on public.app_settings
  for select
  to anon, authenticated
  using (id = 'global');

grant select on public.app_settings to anon, authenticated;
revoke insert, update, delete on public.app_settings from anon, authenticated;
grant select, insert, update, delete on public.app_settings to service_role;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users (id) on delete set null,
  target_user_id uuid references auth.users (id) on delete set null,
  acao text not null,
  detalhes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs (created_at desc);

alter table public.admin_audit_logs enable row level security;

create or replace function public.current_user_is_owner()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and plano = 'dono'
      and bloqueado = false
  );
$$;

revoke all on function public.current_user_is_owner() from public;
grant execute on function public.current_user_is_owner() to authenticated;

drop policy if exists "Dono le historico administrativo"
  on public.admin_audit_logs;

create policy "Dono le historico administrativo"
  on public.admin_audit_logs
  for select
  to authenticated
  using ((select public.current_user_is_owner()));

grant select on public.admin_audit_logs to authenticated;
revoke insert, update, delete on public.admin_audit_logs from anon, authenticated;
grant select, insert, update, delete on public.admin_audit_logs to service_role;
grant usage, select on sequence public.admin_audit_logs_id_seq to service_role;

create or replace function public.hook_controlar_cadastros(event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  cadastros_liberados boolean;
begin
  select configuracao.cadastros_liberados
  into cadastros_liberados
  from public.app_settings as configuracao
  where configuracao.id = 'global';

  if coalesce(cadastros_liberados, true) = false then
    return jsonb_build_object(
      'error', jsonb_build_object(
        'http_code', 403,
        'message', 'Novos cadastros estão temporariamente bloqueados pelo administrador.'
      )
    );
  end if;

  return '{}'::jsonb;
end;
$$;

revoke all on function public.hook_controlar_cadastros(jsonb) from public, anon, authenticated;
grant execute on function public.hook_controlar_cadastros(jsonb) to supabase_auth_admin;
grant usage on schema public to supabase_auth_admin;
grant select on public.app_settings to supabase_auth_admin;

comment on function public.hook_controlar_cadastros(jsonb) is
  'Auth Hook Before User Created: impede novos cadastros quando a opção global estiver desativada.';

-- Primeira conta Dono autorizada pelo responsável do MahaFinance.
update public.profiles
set plano = 'dono'
where id = (
  select id
  from auth.users
  where lower(email) = lower('mahafinance2026@gmail.com')
);
